### ISSUE TITLE
Combining marks have undesirable side effects

### ISSUE THREAD

**Issue by springcomp** [tbolon/optimized-azerty-win#13]
## Description

In the current source code, many dead-keys are triggered using combining Unicode symbols. However, the default behaviour of a keyboard is to output the dead-key trigger if no matching composite pair has been found.

For instance, the combining acute accent does not have a matching composite pair for letter `x`. Therefore, typing <kbd>AltGr</kbd>+<kbd>é</kbd>, <kbd>x</kbd> produces a sequence of Unicode characters consisting of, first, a combining acute accent, and then the letter `x`.

In that case, the combining acute accent is applied to the preceding character, thus modifying text that the user typed. For instance, if the preceding character is a `é`, the sequence will produce the string `é́x` containing a doubly accented e letter which does not seem correct.

## Proposal

The first solution I came up with was to prevent a dead-key from outputting any character when a composite pair does not match. This has two drawbacks. The first is that one must specify explicitely every mapping as producing a `NUL` character in each dead-key table. The second drawback is that it is not consistent with the behavior of current keyboards.

For instance, typing <kbd>^</kbd>+<kbd>p</kbd> produces the string `^p`.

Therefore, I propose to replace combining dead-letter triggers with non-spacing, non-combining variants.

### Implementation

For most common combining unicode symbols, there exists a non-combining variant. For instance, the following combining characters have a direct non-combining variant:

- COMBINING ACUTE ACCENT -> ACUTE ACCENT
- COMBINING BREVE -> BREVE
- COMBINING CARON -> CARON
- COMBINING CEDILLA -> CEDILLA
- COMBINING DIAERESIS -> DIAERESIS
- COMBINING DOT ABOVE -> DOT ABOVE
- COMBINING DOUBLE ACUTE ACCENT -> DOUBLE ACUTE ACCENT
- COMBINING GRAVE ACCENT -> GRAVE ACCENT
- COMBINING MACRON -> MACRON
- COMBINING OGONEK -> OGONEK
- COMBINING RING ABOVE -> RING ABOVE

Some characters have an equivalent which produces a different glyph but can safely be used:

- COMBINING SHORT STROKE OVERLAY -> HYPHEN MINUS (`-`)
- COMBINING SHORT SOLIDUS OVERLAY -> SOLIDUS (`/`)
- COMBINING TILDE -> TILDE (`~`)
- COMBINING CIRCUMFLEX ACCENT -> CIRCUMFLEX ACCENT (`^`)
- COMBINING DOUBLE GRAVE ACCENT -> DOUBLE GRAVE ACCENT (`˵`)

However, some combining characters do not have an equivalent non-spacing variant. My proposal is to replace the following characters:

- COMBINING MACRON BELOW -> UNDERBAR (`_`)
- COMBINING INVERTED BREVE -> TIE (`⁀`)
- COMBINING DOT BELOW -> DOT (`.`)
- COMBINING COMMA BELOW -> COMMA (`,`)

I'm not particularly satisfied with the TIE (`⁀`) but I could not find a better match.

I believe this is the most sensible thing to do, in order to prevent undesirable side effects while minimizing surprising behavior for the end-user.

Please let's use this proposal for discussion.

**Comment by springcomp** [comment]
Nevertheless, the norm mandates that complex characters must be supported. For instance, a `ḉ` that consists in a sequence of LATIN SMALL LETTER C WITH CEDILLA, COMBINING ACUTE ACCENT. So, clearly, we need the combining characters.

My solution would be to add a mapping to the dead key table for the character to itself.

Thus, when one wants to create arbitrarily complex characters, the dead-key trigger must be doubled to produce a combining mark that applies to the previous character.

![image](https://user-images.githubusercontent.com/8488398/57397823-d195ca80-71cd-11e9-98ff-12227ca97a34.png)

For instance, ignoring the fact that `ç` is already available on the layout, to produce the example character, one would type the following combination:

- <kbd>AltGr</kbd>+<kbd>v</kbd> to select the dead-letter cedilla.
- <kbd>c</kbd> to produce `ç`
- <kbd>AltGr</kbd>+<kbd>é</kbd>, <kbd>AltGr</kbd>+<kbd>é</kbd> to produce a combining acute accent mark, thus producing the final character.

In that case, the default behaviour is not suprising for an end-user. At the same time, complex characters can be produced.

I have tested this successfully in a preliminary work that I intend to publish as a PR if this proposal goes through.

However, there is still a few issues with regards to the norm, that mandates that doubling a dead-key combining mark should select the 'BELOW' variant. For instance, hitting twice the 'COMBINING MACRO' should select the 'COMBINING MACRO BELOW' instead.

**Comment by tbolon** [comment]
I agree with you with the fact that, when possible, the new behavior should match the current one.

Displaying the combining character when pressing the key for the first time is not ideal, because can be disturbing for the user. The idea of displaying it only when the combination is pressed a second time is a nice way to allow any arbitrarily complex characters.

Feel free to suggest a PR.
