### ISSUE TITLE
Enable GitHub Pages-based documentation

### ISSUE THREAD

**Issue by springcomp** [tbolon/optimized-azerty-win#53]
@tbolon, I have pushed [a new branch](https://github.com/tbolon/optimized-azerty-win/blob/gh-pages/index.md) to publish GitHub Pages-based documentation for the layout. Would you please [setup GitHub Pages publishing](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages) in the repository settings ?

**Comment by tbolon** [comment]
The site has been published https://tbolon.github.io/optimized-azerty-win/
